# Generated by Django 3.1.2 on 2021-05-31 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210528_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='주소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='kakao',
            field=models.CharField(choices=[('kakao', 'kakao'), ('none', 'none')], default=django.utils.timezone.now, max_length=8, verbose_name='카카오톡여부'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_store',
            field=models.CharField(default=1, max_length=128, verbose_name='카카오톡매장명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=16, verbose_name='전화번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.CharField(default=1, max_length=128, verbose_name='매장명'),
            preserve_default=False,
        ),
    ]
